### ISSUE TITLE
Organizer and user roles are not properly set up

### ISSUE THREAD

**Issue by Shkrt** [rails-up/zakupki#30]
Если у пользователя есть только роли "organizer" и "user", то он не может попасть на страницу просмотра закупки. При этом незарегистрированный пользователь и пользователь с ролью "moderator" могут.

**Comment by badimalex** [comment]
https://github.com/rails-up/zakupki/pull/64
готово. только неавторизованный тоже не может создавать закупки, в соответсвии с ТЗ(см. трелло).
