### ISSUE TITLE
Список городов

### ISSUE THREAD

**Issue by Fatpaher** [rails-up/zakupki#43]
Я занимался последнее время таском 

> Отдельный rake-таск или job для обновления списка городов в БД с помощью geonames
Таск должен по крону, раз в неделю подключаться к api geonames и обновлять список городов в БД. Процесс должен быть фоновый.

Пробывал много способов, как это можно было бы реализовать, но все они не идеальны и не решают поставленную задачу. Вот проблемы с которыми я столкнулся ну или предпологаю невозможность их решения:

- Привязываться к городам одной страны, не очень рационально, но в то же время  к примеру файл с базой данных из Вконтакте со списком всех городов весит около 1.2 гигабайта

- Всегда  найдется город, который не находится в списке

- Есть города с одинаковыми названиями

- Извлечь русские названия из базы данных сервисов типа geonames не всегда представляется возможным

- Обычным пользователям не стоит давать возможность самим вводить города а то будут _Санкт-Петербург_, _Санк-Питербург_ и так далее

Что же я в итоге предлагаю сделать

- Добавить к модели City поля region и country

- Сделать на основе новой схемы минимальную базу данных

- Сделать возможность модераторам добавлять новые города

- Сделать кнопку `Нет вашего города в списке? Создайте его` ну или как-то так, чтобы отправлять заявку

Может быть я просто чего-то не знаю или не понимаю, поэтому создал этот issue для обсуждения

**Comment by Shkrt** [comment]
На гитхабе видел готовый seeds.rb со странами и городами в каждой из стран, т.е. все города мира с названиями на русском языке. Вот он https://github.com/cbrwizard/world_city_names_russian
Можно тогда действительно БД переделать под этот файл. Добавляют новые города пусть администраторы.

**Comment by nevidnichiy** [comment]
Как вариант - брать автокомплитом по API название и id, и при создании закупки писать город в базу, для локального поиска. Если город с таким id уже есть, то не писать. Если api сервиса где это все будем брать не отвалится, то такая схема должна работать

**Comment by Fatpaher** [comment]
@nevidnichiy я думал так сделать через гугл API, но там вывести просто название города нельзя, очевидно из-за того что у городов могут быть одинаковые названия.
@Shkrt Этот сид нам дудмаю очень даже подходит, @nemelnikov скажет, но я лично за такой вариант, единственное, что саму базу данных можно сделать немного короче, но это уже технические подробности

**Comment by nemelnikov** [comment]
Да, можно переделать, чтобы юзать этот seed. Если там какого-то города нет, то через админа можно будет решать, оставить просто текстовую подсказку с указанием почты и всё.
Но вероятность стремится к нулю, что какого-то города не будет.

А в текущем сиде же итак уже очень много городов? зачем ещё внешний брать? или он совсем-совсем полный?

**Comment by Fatpaher** [comment]
@nemelnikov я подозреваю что эта база, сделана теми же людьми сделана, что используем мы, судя по ее строению. 

На время разработки можно и ее оставить, только немного отрефакторить, но там только города России, а, например, СНГ там нету. То есть прост когда дойдет до релиза, держать во внимании, что лучше будет добавить все города и страны что сделать будет не сложно.

**Comment by webchi** [comment]
https://kladr-api.ru/examples есть ещё по городам России
